### ISSUE TITLE
Render Distance 

### ISSUE THREAD

**Issue by DeadmanTheGod** [19PHOBOSS98/Mirage#4]
It would b nice to increase or decrease the render distance.  Some big mirages render distances r too low if you are either too close or slightly far it disappears which makes it annoying if u want it as a center piece to a bigger build or a nice landmark for a village.

**Comment by 19PHOBOSS98** [comment]
Oh yeah, the distance bug. The mirage turns shadowy if you center it too far away from the projector. It shouldn't do that. Im still looking into why it happens but in my experience it works fine with shaders on. BSL to be exact

**Comment by 19PHOBOSS98** [comment]
Right now, the mirage projector is fixed to start rendering within 512 blocks... how big of a rendering distance do you actually need it to be?

**Comment by DeadmanTheGod** [comment]
thanks for the reply. idk when im either too close or too far it disappears .... i just got home so here r screenshots .. also this is the moving whale i just used as a test b4 i make own. I plan to make something on that scale. The first pic is the furthest its visible. 
The second pic is when it disappears as i get close. 3rd is the when it start to disappear when i go back. n the 4th is when it stops being visible looking from the top. it would b nice to see it from all angles n close like 20 block.  i have an amusement park and want to make a moving scene thats similar to the whale that people can walk under n see.. If it can done cool if not dont stress yourself. 
![2024-04-10_20 21 42](https://github.com/19PHOBOSS98/Mirage/assets/116610696/9bad0110-706b-40aa-90f7-fbfe1719a87e)
![2024-04-10_20 22 02](https://github.com/19PHOBOSS98/Mirage/assets/116610696/6d477caf-a162-4485-814d-747073d3766c)
![2024-04-10_20 22 45](https://github.com/19PHOBOSS98/Mirage/assets/116610696/c502d3f0
![2024-04-10_20 23 05](https://github.com/19PHOBOSS98/Mirage/assets/116610696/b49533f6-8407-489a-9675-18cc7e182298)
-bbfb-4922-9c64-17f9be623b91)

**Comment by 19PHOBOSS98** [comment]
Too close or too far... as long as you're close enough to the projector (or atleast the projector is in view) it should render...

Where did you say you put down the projector? Is it far away behind the camera?

Also are you on fabric or forge?

**Comment by DeadmanTheGod** [comment]
forge 1.19.2  .. ahh its a little to the left of the projector cuz setting the scale values from the base 0.2xxx to 2 moved it there.. if i made an error lmk so i can correct it to keep the scale big but move closer to the projector.

**Comment by 19PHOBOSS98** [comment]
so what you're saying is the projector is in the shot somewhere right next to the whale? can you send me a copy of the world so I can see for myself what's going on?

**Comment by DeadmanTheGod** [comment]
yes i had to upload it to my gdrive since its to big to post here  . https://drive.google.com/drive/folders/1LnXMztlc1X68IcDuLGax1F4aqYQeQ5vz?usp=sharing i was testing other mods for may monthly server update so this isnt spawn so i will post a screenshot with the coords.. look for a stone pillar with a gold block. i placed it to make it easier for you to go in if  u plan on spawning into the world.. just note since i have world gen mods it may look weird if u dont have them. 
![Screenshot 2024-04-10 220240](https://github.com/19PHOBOSS98/Mirage/assets/116610696/2f894271-2dde-4eae-8955-b0da30474fa7)

**Comment by 19PHOBOSS98** [comment]
how far did you say you've got your render distance set to?

**Comment by DeadmanTheGod** [comment]
for the testing i have it on 32 .. i usually play on 14-16 tho.. the rest of the players on the server play on like 10 n below.. but since this is a test single player world i dont think theirs matter rn

**Comment by 19PHOBOSS98** [comment]
how about your "simulation distance"?

**Comment by DeadmanTheGod** [comment]
maxed out everything maxed for testing

**Comment by DeadmanTheGod** [comment]
here is what i mean when i said its off to the left a little bit. and if i were to go closer to the whale at its end position it disappears 
![2024-04-10_22 30 18](https://github.com/19PHOBOSS98/Mirage/assets/116610696/00b8963b-a958-4154-afc1-28bdc3c0e883)
![2024-04-10_22 28 48](https://github.com/19PHOBOSS98/Mirage/assets/116610696/a3aa6198-75e6-40a9-8687-dde867e5a168)
 n here is also the book settings 
![Screenshot 2024-04-10 223403](https://github.com/19PHOBOSS98/Mirage/assets/116610696/9ad6a528-fbd8-49ac-8f63-6e0ddcd196fc)

**Comment by 19PHOBOSS98** [comment]
I've set my render distance to 32 as well and it seems to be working fine. At least up until the projector's chunk gets unloaded when I get far enough away:
https://youtu.be/0kWZmdd-5JE

Maybe that's why? it renders within 512 blocks but if the chunk that it's on isn't loaded then it wouldn't work anyways...
When the chunk reloads, the projector also needs to buffer the mirage again

**Comment by DeadmanTheGod** [comment]
i think the far distance is ok but the close distance goes invisible unless its because its not under the projector n then that would b my error. see i fly close to it and slightly above it n it disappears. im still close to the pillar. if im wrong after this n its working as intended then im sorry for wasting ur time. like i said the reason i want it visible close from under and above is to put some moving things in the amusement park when riding rides. if i have to play with the book settings to get it right then lmk n i will start messing with the book.  https://www.youtube.com/watch?v=D38pQ21723E

**Comment by 19PHOBOSS98** [comment]
From your video it disappears when you crossed the river. I tried replicating this but everything seems fine:
https://youtu.be/qoKSEcH-fSk

in the video you sent, for some reason the projector isn't rendering itself when you looked down at it:
![image](https://github.com/19PHOBOSS98/Mirage/assets/37253663/21ccabab-eb41-40f3-a89e-a77245918b3d)

moreover, it looks like the projector's render-bounding-box is way smaller than usual judging by the way you flew in and out of range of the projector at the end of the video...

I think it's because of another mod. Might be some performance mod that messes with "BlockEntity Rendering". Try rendering the whale with just Mirage and Oculus installed and lmk what you find

PS: try using the default Oculus and shader settings

**Comment by DeadmanTheGod** [comment]
thanks it was the BlockEntity Rendering setttings.. i forgot i turned it off with embeddium++ when i was testing Valkyrien Skies n   emdeddium  block rendering bug.. it works now .. thanks again

**Comment by 19PHOBOSS98** [comment]
Slr, I only could manage to leave a thumbs up at the time. Happy to help!
