### ISSUE TITLE
<title>mirages dont show up in multiplayer

### ISSUE THREAD

**Issue by ABSOLUTEMAX123** [19PHOBOSS98/Mirage#5]
### This issue occurs when only Mirage is installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

when loading a mirage, it only shows for the player making it

### Issue reproduction

load into a server
try to show your friend a mirage

**Comment by 19PHOBOSS98** [comment]
I think I found the issue. I'll be back with a fix :)

**Comment by DeadmanTheGod** [comment]
when multiplayer support is added i will for sure add this to my multiplayer server

**Comment by ABSOLUTEMAX123** [comment]
has the fix been posted yet?

**Comment by 19PHOBOSS98** [comment]
It took longer than I expected but it should be fixed now. Let me just prep the new Modrinth files

**Comment by 19PHOBOSS98** [comment]
I'm just going to close this thread for now. You guys just reopen it if you find anything wrong.
